### ISSUE TITLE
Fails on regions without Glacier

### ISSUE THREAD

**Issue by myleshosford** [awslabs/aws-security-benchmark#11]
Create-benchmark-rules.yaml fails when deploying into a region that does not have Glacier (like Singapore)

Error:

S3BucketForGovernance	"This region does not support transition to GLACIER"

Propose to fix using the following(would love to know a smarter way):

StorageClass:
!FindInMap [RegionMap, !Ref "AWS::Region", storage]

With a mapping:

  Mappings: 
    RegionMap: 
      us-east-1: 
        storage: "GLACIER"
      us-east-2: 
        storage: "GLACIER"
      us-west-1: 
        storage: "GLACIER"
      ca-central-1: 
        storage: "GLACIER"    
      us-west-2: 
        storage: "GLACIER"
      eu-west-1: 
        storage: "GLACIER"
      sa-east-1: 
        storage: "GLACIER"
      ap-southeast-1: 
        storage: "STANDARD_IA"
      ap-southeast-2: 
        storage: "GLACIER"
      ap-northeast-1: 
        storage: "GLACIER"

**Comment by barnesrobert** [comment]
Approved PR.
