### ISSUE TITLE
YAML errors

### ISSUE THREAD

**Issue by ShadySQL** [awslabs/aws-security-benchmark#17]
While trying to deploy this cloudformation stack:

https://github.com/awslabs/aws-security-benchmark/blob/master/architecture/create-benchmark-rules.yaml

I get this error:

Template validation error: Template format error: Unresolved resource dependencies [FunctionForEvaluateKeyRotationRule] in the Resources block of the template

**Comment by barnesrobert** [comment]
This error occurred when selecting a Level 1 profile; Level 2 conditions have now been added for Rule 2.8 dependencies.

Thank you for submitting the issue.
