### ISSUE TITLE
Error with JSON file

### ISSUE THREAD

**Issue by ShadySQL** [awslabs/aws-security-benchmark#18]
While trying to launch:

https://github.com/awslabs/aws-security-benchmark/blob/master/aws_cis_foundation_framework/aws-cis-foundation-benchmark-checklist-lambdarole.json

I get the following error:

Template validation error: Invalid template property or properties [Version, Statement]

**Comment by HenrikJaySmith** [comment]
Hi,

That json structure is actually just a policy doc used when creating a IAM policy to attach to a IAM role used by Lambda, it is not a CloudFormation Template.
You can follow this guide how to create the policy to attach to the role used by the Lambda function http://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_managed-policies.html

I will also add to the backlog to create a CloudFormation template for the benchmark.
