### ISSUE TITLE
Deploying create-benchmark-rules.yaml

### ISSUE THREAD

**Issue by cpollard0** [awslabs/aws-security-benchmark#2]
I get the following issue when tyring to deploy the create-benchmark-rules.yaml cloudformation templtae: 

Template validation error: Template may not exceed 460800 bytes in size.

**Comment by andrewkrug** [comment]
@cpollard0 try putting the template in an S3 bucket and using it that way.  Cloudformation will let you reference an S3 URL when you call create stack.

**Comment by HenrikJaySmith** [comment]
Correct, please use --template-url and point to S3 location of the template.

**Comment by cpollard0** [comment]
That did it, thanks!

**Comment by barnesrobert** [comment]
Please see this [link](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html) on AWS CloudFormation limits.

The template body size in a request is limited to **51,200** bytes; the limit increases to **460,800** bytes when using S3.
