### ISSUE TITLE
The aws-cis-foundation-benchmark-checklist-lambdarole.json file doesn't work with CloudFormation

### ISSUE THREAD

**Issue by ananthu99** [awslabs/aws-security-benchmark#20]
Hi, 
I get the following error when trying to launch the CF Template for the aws-cis-foundation-benchmark-checklist-lambdarole.json file.  

Any ideas on why the json file doesn't work?

Template validation error: Invalid template property or properties [Version, Statement]

Thanks,
Anand.

**Comment by ananthu99** [comment]
I had thought that the JSON file was used to create the IAM policy using CloudFormation.  I ended up creating a IAM policy using the content from the file.  So, this issue can be closed.

**Comment by HenrikJaySmith** [comment]
Working on a CFn template for this

**Comment by ananthu99** [comment]
Thanks a lot HenrikJaySmith.  I hope to be able to use it once it is available.  Please keep me updated on this. 

Thank you, 
Anand.
