### ISSUE TITLE
CIS 1.14 Evaluation Script (Root MFA enabled)

### ISSUE THREAD

**Issue by markusbecker** [awslabs/aws-security-benchmark#24]
Hey Guys,

first: wow, great work on all of this. Im already a big fan of your work regarding automation of AWS compliance. 

Is there maybe a typo when it comes to evaluating root account MFA CIS 1.14? Is seems like you are evaluating an account to have an MFA for root by default and when you find one you evaluate to "false".

```    
result = False
(...)
if "mfa/root-account-mfa-device" in str(pagedResult):
        #failReason = "Root account not using hardware MFA"
        result = False
```

I can submit a pull request if you like, im just quite new to github and still need to figure out how to do that :)

best regards,
Markus

**Comment by HenrikJaySmith** [comment]
Hi Markus,
Thanks for the feedback.
Regarding 1.14, the behavior is correct. We are verifying that the root user have a physical MFA. If we find that string it means that a virtual MFA is being used.
I did however just pushed an update that prevents a false positive for 1.14 when no mfa is used.

Thanks!

**Comment by markusbecker** [comment]
Alright, that was exactly my problem. The report was telling me that there was no MFA enabled for root, but hardware MFA is enabled. I guess its fixed now. Thanks!

**Comment by HenrikJaySmith** [comment]
Great, thanks for reporting and let us know if you have other issues or improvement requests.
