### ISSUE TITLE
 Rules > DetectEc2TerminationEvents is not working

### ISSUE THREAD

**Issue by dark-spark2** [awslabs/aws-security-benchmark#26]
Hi,
only after adding  "TerminateInstances" to eventName the rule worked.
has amazon changed the event name ? 
{
  "detail-type": [
    "AWS API Call via CloudTrail"
  ],
  "detail": {
    "eventSource": [
      "ec2.amazonaws.com"
    ],
    "eventName": [
      "TerminateInstance",
      "TerminateInstances"
    ]
  }
}

**Comment by barnesrobert** [comment]
Thank you for identifying this issue. The event should indeed be "TerminateInstances". This has just been fixed.
