### ISSUE TITLE
False positive on 1.24 Config Rule

### ISSUE THREAD

**Issue by asagage** [awslabs/aws-security-benchmark#27]
The Rule 1.24 Lambda function is returning a false positive for policies containing "*" anywhere in the action.  

The policy should be looking for an exact match, but it is matching if the field contains * even if it is something like "ec2:*".

**Comment by HenrikJaySmith** [comment]
Looking into this.

**Comment by HenrikJaySmith** [comment]
Can you verify that you have the latest version of the script since I believe this was fixed a while  ago.
If you have the latest, can you post the policy in question without potential sensitive information so I can verify since it is not failing in my tests.

**Comment by HenrikJaySmith** [comment]
Just checking if you had a chance to look at my question above?

**Comment by HenrikJaySmith** [comment]
Closing due to no response
