### ISSUE TITLE
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)

### ISSUE THREAD

**Issue by neomatic999** [awslabs/aws-security-benchmark#28]
Hi there

We think we have everything correctly configured but the script always stops with the error detailed below. Can you help??  

START RequestId: 89291a84-36f1-11e7-a7f4-1f479e181a6e Version: $LATEST
iterator should return strings, not bytes (did you open the file in text mode?): Error
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 2244, in lambda_handler
    cred_report = get_cred_report()
  File "/var/task/lambda_function.py", line 1943, in get_cred_report
    for row in reader:
  File "/var/lang/lib/python3.6/csv.py", line 111, in __next__
    self.fieldnames

**Comment by HenrikJaySmith** [comment]
Looking into this

**Comment by neomatic999** [comment]
Hi, thank you. 

We are one of your larger enterprise customers in APAC. I have also spoken to the local AWS team to help with this. 

The code seems to fall over in the following section (iterating through reader object):
![untitled](https://cloud.githubusercontent.com/assets/27033272/26179654/4c1b6124-3ba8-11e7-9275-03d0498bc41c.jpg)

**Comment by HenrikJaySmith** [comment]
Can you provide some info on the environment you are running the script on?
OS? Python version?

**Comment by neomatic999** [comment]
Sure, I have tried a few different things. I tried running it as a Lambda function with the Python 3.6 runtime and all other values as default except for timeout which I set to 5 min. 

I have also tried running it on my laptop on Win 10, with the latest version of Python. 

In both examples, I get exactly the same error message.

**Comment by HenrikJaySmith** [comment]
I have not yet test it against Python 3.6 but added it to todo.
To verify, can you modify the Lambda function and switch to Python 2.7 to test?

**Comment by neomatic999** [comment]
Hi, yes it is fully working on Python 2.7.Thank you so much. Maybe update the docu on github? Thanks for getting back to me.

**Comment by HenrikJaySmith** [comment]
Will update docs and have on the todo to validate against Python 3.6.
Thanks for reporting.

**Comment by neomatic999** [comment]
No worries, thank you for getting back to us. We are now implementing your scripts across our accounts. I work for Origin Energy, one of the largest energy companies in Australia. I am actually the CISO but I don't mind getting my hands dirty from time to time. Thanks again. 
RegardsChristoph

**Comment by HenrikJaySmith** [comment]
Great to hear, and please send in any feature requests either here or to your account team/me.
I am currently working on some multi account support as well but no ETA.

**Comment by neomatic999** [comment]
Will do, thank you!

**Comment by obijan42** [comment]
It's a python 3 thing.

Fixed it here:
https://github.com/obijan42/aws-security-benchmark/commit/2d748b1bb8d97d2fab4bc8dbc294b4b1c00442c8

**Comment by chilithomas** [comment]
Had same error but saw this closed case and code seems to be working now thanks for comment @obijan42.

**Comment by bhushan-phynd** [comment]
This issue is occurring with Python 3.6, 3.8.
