### ISSUE TITLE
HTML format

### ISSUE THREAD

**Issue by tinawalt** [awslabs/aws-security-benchmark#3]
Anyone else having issues with html format output? 

1: KeyError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 2019, in lambda_handler
htmlReport = json2html(controls)
File "/var/task/lambda_function.py", line 1849, in json2html
if str(controlResult[n+1][x+1]['Result']) == "False":
KeyError: 1

**Comment by HenrikJaySmith** [comment]
I am currently rebuilding the control reporting functions and will push a new version tomorrow (12/7). Will update this post if you can try that version before we dive deeper into this error.

**Comment by HenrikJaySmith** [comment]
Just pushed the new version that has a different control management solution, could you please test that version?

**Comment by HenrikJaySmith** [comment]
Just checking if you have had a chance to test the new version?

**Comment by HenrikJaySmith** [comment]
Closing issue due to no feedback on updated code and no tests show the error. Please reopen if still error.
