### ISSUE TITLE
Documentation issue - don't include CIS PDF

### ISSUE THREAD

**Issue by worldofdub** [awslabs/aws-security-benchmark#38]
A link to the CIS Benchmarks document would be a better approach rather than including the PDF in this repository.

(https://d0.awsstatic.com/whitepapers/compliance/AWS_CIS_Foundations_Benchmark.pdf or https://www.cisecurity.org/benchmark/amazon_web_services/)

**Comment by HenrikJaySmith** [comment]
This is done per agreement with CIS
