### ISSUE TITLE
Can we please get this updated for benchmark v2.1.0?

### ISSUE THREAD

**Issue by skyzyx** [awslabs/aws-security-benchmark#70]

**Comment by netflash** [comment]
@skyzyx are you sure this issue is correct ?
There is CIS Amazon Linux Benchmark v2.1.0
and
CIS Amazon Web Services Benchmarks v1.1.0

To my understanding this repository represents the latter.

**Comment by skyzyx** [comment]
My understanding is that this repository supports the older 1.1.0 version.

2.1.0 was recently approved and published. 2.0.0 was around even before that.

So my question is — can the work be done to bring compliance up-to-date with the current CIS Benchmark?

**Comment by skyzyx** [comment]
Gah. I’m stupid. Nevermind.

**Comment by markusbecker** [comment]
Are you sure that you are not talking about the currently discussed version
CIS Amazon Web Services Benchmarks v1.2.0. 

It is currently in draft status and therefore not yet released. 

https://workbench.cisecurity.org/benchmarks/245

**Comment by bwhaley** [comment]
It is in fact released now. I'm reluctant to open a new issue on the matter - perhaps this issue can be reopened and the maintainers can mentioned if/when they expect to support `v.1.20`?
