### ISSUE TITLE
do we still need InstancesMustUseIamRoles Rule in CIS Template?

### ISSUE THREAD

**Issue by philipakash** [awslabs/aws-security-benchmark#75]
I am opening this issue to understand if we still need this rule `InstancesMustUseIamRoles` in CIS Profile.
I know AWS changed the way how we attach the roles to the EC2 instances. Earlier we could not assign an IAM instance Role to EC2 instances after they were launched and were in running state and back then keeping this rule `InstancesMustUseIamRoles` helped avoiding the storage of AWS Credentials in the Server.

`InstancesMustUseIamRoles` Rule checks for EC2 instances which doesn't have any IAM Roles attached to it and marks the Instance as non-compliant if found without a role.  But Many of the instances don't need the Roles  and if needed can be attached later.
Any one here having any thoughts on this ?? Do we still need to keep this rule or disable this ?
Or Am I missing something ?

**Comment by barnesrobert** [comment]
Thanks for the comment. This controls are published by CIS. This control in particular predates the feature allowing you to attach a role to an running instance, so whether you to disable the control is up to your discretion. A CIS benchmark refresh may not include this particular control.

I hope this helps.
